name: Compile Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: sudo bash install.sh
      
      - name: Compile kernel
        run: bash .github/workflows/compile.sh
      
      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-qemu
          path: |
            kernel
            kernel.bin
          retention-days: 30